---
- name: Instal Grafana and Prometheus
  hosts: all
  become: true

- import_playbook: tasks/grafana-setup.yml
- import_playbook: tasks/prometheus-setup.yml
- import_playbook: tasks/apache-setup.yml
